name: Maven Build and SonarQube

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Project
        run: mvn clean package
        working-directory: java-project-maven-new-master/java-project-maven-new-master

      - name: SonarQube Scan
        run: |
          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:4.0.0.4121:sonar \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        working-directory: java-project-maven-new-master/java-project-maven-new-master

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload WAR to S3
        run: |
          aws s3 cp \
          java-project-maven-new-master/java-project-maven-new-master/target/myapp.war \
          s3://${{ secrets.S3_BUCKET }}/
